/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lenguajesproyecto2;

/**
 *
 * @author ErikssonHerlo
 */
public class InformacionEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form InformacionEstudiante
     */
    public InformacionEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Fondo1 = new javax.swing.JLabel();
        Titulo3 = new javax.swing.JLabel();
        Titulo4 = new javax.swing.JLabel();
        Titulo5 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(254, 254, 254));
        Titulo.setText("INFORMACION DEL ");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 560, 110));

        Titulo2.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(254, 254, 254));
        Titulo2.setText("Eriksson José Hernández López");
        getContentPane().add(Titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 410, 80));

        Titulo1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 48)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(254, 254, 254));
        Titulo1.setText("ESTUDIANTE");
        getContentPane().add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 370, 110));

        Salir.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 310, 40));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/me2.jpg"))); // NOI18N
        Fondo1.setMaximumSize(new java.awt.Dimension(800, 467));
        Fondo1.setMinimumSize(new java.awt.Dimension(800, 467));
        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 270));

        Titulo3.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        Titulo3.setForeground(new java.awt.Color(254, 254, 254));
        Titulo3.setText("201830459");
        getContentPane().add(Titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 150, 70));

        Titulo4.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        Titulo4.setForeground(new java.awt.Color(254, 254, 254));
        Titulo4.setText("Lenguajes Formales y de Programación");
        getContentPane().add(Titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 490, 80));

        Titulo5.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 24)); // NOI18N
        Titulo5.setForeground(new java.awt.Color(254, 254, 254));
        Titulo5.setText("Ingeniería en Ciencias y Sistemas 2019");
        getContentPane().add(Titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 490, 80));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/library.jpeg"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(800, 467));
        Fondo.setMinimumSize(new java.awt.Dimension(800, 467));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -70, 930, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Titulo3;
    private javax.swing.JLabel Titulo4;
    private javax.swing.JLabel Titulo5;
    // End of variables declaration//GEN-END:variables
}
